import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
function About() {
  return (
    <div>
      <Head>
        <title>Vekser-About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <section className="section">
        <div className="container">
          <div className="row">
            <div className="col-md-6 pt-5">
              <h1 className="">Some background</h1>
              <p className="pt-3">
                Vekser is a venture capital firm founded in 2022 in Miami,
                Florida. The firm is focused on backing entrepreneurs who are
                innovative, disruptive, and willing to challenge established
                norms in big industries. Vekser invests in seed-stage
                technologies and practical ideas in various sectors, including
                logistics, real estate, SaaS, marketing, beauty, fashion, and
                entertainment. The firm has a global reach with investments in
                the US, Peru, Israel, Portugal, India, the Netherlands, and the
                UK. Vekser prides itself on partnering with its portfolio
                companies and providing support beyond just financial
                investment.
              </p>
            </div>
            <div className="col-md-6">
              <Image
                src="/images/vekser-team.webp"
                alt="vekser-team"
                className="img-fluid"
                width={500}
                height={500}
                priority
              />
            </div>
          </div>
        </div>
      </section>
      <section className="section">
        <div className="container">
          <div className="row">
            <div className="col-md-6">
              <Image
                src="/images/John Daniel.webp"
                className="img-fluid"
                alt="John Daniel"
                width={400}
                height={600}
                priority
              />
            </div>
            <div className="col-md-6">
              <h1 className="">About John</h1>
              <p className="">
                John Vekser (October 30, 1980) is a successful real estate and
                technology investor, with a career spanning over 25 years in
                various business ventures. He has achieved notable success in
                the technology, fashion & beauty, and logistics industries, with
                his essential lessons about client and customer relationships
                helping him to create companies that have revolutionized the
                face of technology. John's story is one of persistence and
                determination, as he started his clothing line from the back of
                his car before moving into logistics and eventually technology.
                His investments in startups that brought instant quoting online
                revolutionized the transportation industry and resulted in
                significant exits. John's current focus is on real estate and
                SaaS companies, resulting in substantial growth for his business
                online. His success serves as a reminder that persistence,
                determination, and a willingness to adapt are key to success in
                any industry.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="row text-center">
            <h1 className=" mb-5">
              Supporting visionary founders <br /> in achieving their radical
              ideas.​
            </h1>
            <p className="mb-5">
              Our aim is to make an impact with companies that solve social and
              <br />
              economic issues and will help define a new era of technology.
              <br />
              We have created top-of-the-line executive resources platform of
              media, executives, technicals, marketing, <br /> technology and
              call centers in 6 countries that ensures our commitment in our
              portfolio companies to grow their businesses globally
            </p>
          </div>
          <div className="row mt-5 mb-5">
            <div className="text-center">
              <Link
                href="/contact"
                passHref
                className="btn btn-primary my-button"
              >
                Invest with us
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default About;
