import React from "react";
import Head from 'next/head';
import Link from "next/link";
import Image from "next/image";
function About() {
  return (
    <div>
       
    <Head>
      <title>Vekser-About Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    </Head>

      <section className="section">
        <div className="container">
          <div className="row">
            <div className="col-md-6 pt-5">
              <h1 className="b-5">Some background</h1>
              <p className="pfont pt-3">
                Founded in Miami, Florida, in 2022, Vekser is a venture capital
                firm that backs disruptive entrepreneurs that are bold and
                courageous in taking on big industries and distrusting the
                norms. Vekser focuses on seed-stage technologies and practical
                ideas in logistics, real estate, SaaS, marketing, beauty,
                fashion, and entertainment in the US, Peru, Israel, Portugal,
                India, Netherlands, and the UK
              </p>
            </div>
            <div className="col-md-6">
              <img
                src="./images/vekser-team.png"
                alt="vekser-team"
                className="img-fluid"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="section">
        <div className="container">
          <div className="row">
            <div className="col-md-6">
              <img src="./images/John Daniel.png" alt="John Daniel" />
            </div>
            <div className="col-md-6">
              <h1 className="b-5">Reimagining capital investments</h1>
              <p className="b-5 pfont">
                John Daniel (October 30, 1980) is a real estate and technology
                Investor in disruptive businesses. An Innovative leader with
                over 25 years in business with multiple successful exits in
                technology, fashion & beauty, and logistics spaces. John’s
                success in business ventures began with the launch of Dandino, a
                clothing brand that taught him lessons about client and customer
                relationships from street level to high-end retail. Investing in
                ReloShip allowed John to enter the shipping industry, which
                cultivated his career until today.Haload’s instant quoting
                provided consumers with logistical services set up online,
                disrupting the competition significantly.Takestar brought speed
                and convenience to the moving industry by quickly providing
                customers access to reliable professionals through mobile
                apps.Sparoll enabled clients across America to find customized
                massage experiences via mobile devices without hassle or
                stress.Algorip automated companies’ reputations online through
                powerful proprietary software. Renesent combines John’s
                experience in start-ups and passion for technology by
                streamlining operations, such as logistics, while Prroperties is
                the best place to find ready-to-move-in residential and
                corporate rentals.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="row text-center">
            <h1 className="b-5 mb-5">
              Supporting visionary founders <br /> in achieving their radical
              ideas.​
            </h1>
            <p className="pfont mb-5">
              Our aim is to make an impact with companies that solve social and
              <br />
              economic issues and will help define a new era of technology.
              <br />
              We have created top-of-the-line executive resources platform of
              media, executives, technicals, marketing, technology and call
              centers <br /> in 6 countries that ensures our commitment in our
              portfolio companies to grow their businesses globally
            </p>
          </div>
          {/* <div className="row mt-5">
            <div className="text-center">
            <Link href="/contact" passHref className="btn btn-primary my-button">
              Invest with us
            </Link>
            </div>
          </div> */}
    
        </div>
      </section>
    </div>
  );
}

export default About;
