import Head from 'next/head'
import React from "react";
import Link from "next/link";
import Image from 'next/image';
function Home() {
  return (
    <>
    <Head>
      <title>Vekser-Home Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    </Head>

    <div>
      <div className="video-container">
        <video src="./video/satyam.mp4" className='video' autoPlay loop muted playsInline />
        <div className="banner-button">
        <Link href="/invest" passHref className="btn my-button btn-primary">
           Get Started Today
              </Link>
          </div>
      </div>
      <section className="section">
        <div className="container">
          <div className="row">
            <div className="col-md-6">
              <h1>
                Big dreams of persistent leaders create great organizations.
              </h1>
              <p className="p-font">
                We invest in individuals that possess the creativity,
                perseverance, and teamwork skills necessary to transform
                innovative ideas into successful businesses through education,
                mentorship, and direct investments.
              </p>
    
            </div>
            <div className="col-md-6">
              <img
                src="./images/vekser-team.png"
                className="img-fluid"
                alt=""
                width=""
              />
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <h1 className="text-center b-5">
                We fuel growth that <br />
                persists over time.
              </h1>
            </div>
          </div>
        
          <div className="row">
            <div className="col-md-4">
              <img
                src="./images/business-partnership.gif"
                className="img-fluid"
                alt="business-partnership"
                width={""}
              />
              <h1 className="text-center b-5">Determined</h1>
              <p className="text-center b-5">
                We concentrate our investments to ensure each founder gets the
                capital & attention they deserve.
              </p>
            </div>
            <div className="col-md-4">
              <img
                src="./images/business-growth.gif"
                className="img-fluid"
                alt="business growth"
                width={""}
              />
                  <h1 className="text-center b-5">Engaged</h1>
              <p className="text-center b-5">
                Together with our founders, we deliver high-impact business
                growth, operational transformation, and leadership development.
              </p>
            </div>
            <div className="col-md-4">
              <img
                src="./images/work-team.gif"
                className="img-fluid"
                alt="work-team"
                width={""}
              />
                  <h1 className="text-center b-5">Diverse</h1>
              <p className="text-center b-5">
                Our team comprises of experts from many industries in corporate
                development, sales, marketing, operations, finance, and supply
                chain.
              </p>
            </div>
          </div>
          <div className="row mt-5">
                <div className="text-center"> 
                <Link href="/about" passHref className="btn my-button btn-primary">Learn More</Link>
                </div>
            </div>
        </div>
      </section>
      <section>
        <div className="container">
            <div className="row">
                <h1 className="text-center b-5">Incredible businesses</h1>
            </div>
            <div className="row mt-5">
             <div className="col-md-4 text-center pt-2"><img src="./images/renesecent-logo.png" className="img-fluid logo  my-button mobile-logo responsive" width={""} alt="renesecent-logo" /></div>
             <div className="col-md-4 text-center"><img src="./images/properties-logo.png" className="img-fluid  mobile-logo   my-button responsive logo" width={""} alt="properties-logo" /></div>
             <div className="col-md-4 text-center pt-2"><img src="./images/Algorip-logo.png" className="img-fluid mobile-logo  my-button responsive logo" width={""} alt="Algorip-logo" /></div>
            </div>
            <div className="row mt-5">
             <div className="col-md-3 text-center pt-2"><img src="./images/Dadadino-logo.png" className="img-fluid  mobile-logo  my-button responsive logo" width={""} alt="renesecent-logo" /></div>
             <div className="col-md-2 text-center pt-2"><img src="./images/sparoll-logo.png" className="img-fluid mobile-logo  my-button responsive logo" width={""} alt="properties-logo" /></div>
             <div className="col-md-2 text-center pt-2"><img src="./images/reloship-logo.png" className="img-fluid mobile-logo   my-button responsive logo" width={""} alt="Algorip-logo" /></div>
             <div className="col-md-2 text-center"><img src="./images/takestar-logo.png" className="img-fluid  mobile-logo  my-button responsive logo" width={""} alt="Algorip-logo" /></div>
             <div className="col-md-3 text-center"><img src="./images/haload-logo.png" className="img-fluid mobile-logo   my-button responsive logo" width={""} alt="Algorip-logo"  /></div>
            </div>
            <div className="row mt-5">
                <div className="text-center"> 
                <Link href="/portfolio" passHref className="btn my-button btn-primary">See Our Portfolio</Link>
                </div>
               
            </div>
        </div>
      </section>
      <section>
        <div className="container">
            <div className="row">
                <h1 className="b-5">News That Matters</h1>
            </div>
            <div className="row">
               
                <div className="col-md-5">
                    <img src="./images/forbes.png" className="img-fluid my-button" alt="forbes" />
                </div>
                <div className="col-md-5">
                <img src="./images/huffspot.png" className="img-fluid my-button" alt="huffspot" />
                </div>
              
                
            </div>
            <div className="row mt-5 mb-5">
                <div className="text-center"> 
                <Link href="/media" passHref className="btn my-button btn-primary">View Gallery</Link>
                </div>
            </div>
        </div>
      </section>
    </div>
     
  </>
  );
}

export default Home;
