import React from "react";
import Link from "next/link";
import Head from "next/head";
import Image from 'next/image';
function Invest() {
  return (
    <div>
      <Head>
        <title>Vekser-Invest Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section className="section">
        <div className="banner">
          <img src="./images/invest-bannere.png" alt="Invest Banner image" />
          <div className="banner-text">
            <h1>
              Why hold a <br />
              community
              <br />
              raise ?
            </h1>
          </div>
        </div>
      </section>
      <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-12 mt-5 mb-5">
                  <h2>To expand coverage</h2>
                  <p>
                    {" "}
                    Through the community raise, we’ll give a network of
                    brilliant entrepreneurs, operators, creatives, marketers,
                    and product leaders access to venture to investors who
                    otherwise wouldn’t be given the opportunity to take part in
                    these deals.
                  </p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12  mb-5">
                  <h2>To broaden the diversity</h2>
                  <p>
                    We welcome applications from all qualified investors,
                    regardless of age, gender, religion, sexual orientation, or
                    physical limitations. Including as many individuals as
                    possible on our companies’ cap tables is critical.
                  </p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12  mb-5">
                  <h2>The competitive advantage</h2>
                  <p>
                    We occasionally use the LP network, which our founders will
                    have access to, to introduce people, share knowledge, aid in
                    fundraising, and hire new employees.
                  </p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <h2>Better deal flows</h2>
                  <p>
                    Our LPs will have their network of entrepreneurs and
                    aspiring founders working on intriguing projects that we
                    want to look at before everyone else.
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-4 mt-5">
              <img
                src="./images/invest-page-graphic.png"
                className="img-fluid"
                alt="invest-graphic"
              />
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="row">
            <div className="col-md-6 mb-5">
              <h2 className="text-style-grow">Let’s Grow Together</h2>
            </div>
            <div className="col-md-6">
              <h2 className="connect-text">Helping you connect businesses</h2>
              <p>
                Businesses are built on relationships, and a single introduction
                can completely alter a founder’s course. If you think of it, we
                probably “know a person” who can help, potential funders,
                influencers, creative agencies, recruitment, vendors, or
                collaborators.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-6 mt-5">
              <h2 className="div-6">You might be the</h2>
              <h2 className="div-7">ONE</h2>
            </div>
            <div className="col-md-6">
              <img
                src="./images/you-might-be-the-one.png"
                className="img-fluid"
                alt="invest-graphic"
              />
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="row">
            <div className="col-md-4">
              <h3>Break the ice</h3>
              <p>
                Without introductions, funding the new generation of founders
                would be impossible.
              </p>
            </div>
            <div className="col-md-4">
              <h3>Assisting portfolio founder</h3>
              <p>
                To make smart introduction requests, we may ping you as they
                hire, raise money, enter new markets, and grow.
              </p>
            </div>
            <div className="col-md-4">
              <h3>Impart wisdom</h3>
              <p>
                We value those with extensive experience and knowledge in
                particular fields or businesses.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="text-center">
              <Link
                href="/contact"
                passHref
                className="btn my-button btn-primary"
              >
                Invest with us
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default Invest;
