import React from "react";
// import Head from "next/head";
import Image from "next/image";
import { NextSeo } from "next-seo";
function Media() {
  return (
    <div>
      {/* <Head>
        <title>Vekser-Media Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head> */}
    
      <NextSeo
            title="Vekser's Captivating Media and Stunning Photos - Explore Our Gallery Now"
            description="Discover the Vekser office through stunning images that showcase the Vekser experience. Immerse yourself in an environment of creativity and collaboration as you explore our cutting-edge workspace."
            keywords="The Vekser experience"
        />
      <section className="section mb-5">
        <div className="container">
          <div className="row">
            <h1 className="text-center mb-5 b-5">The Vekser experience</h1>
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <div className="d-flex flex-column">
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-6.webp"
                width={300}
                height={300}
                priority 
              />
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-1.webp"
                width={300}
                height={300}
                priority 
              />
            </div>

            <div className="d-flex flex-column">
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-2.webp"
                width={300}
                height={300}
                priority 
              />
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-4.webp"
                width={300}
                height={300}
                priority 
              />
            </div>

            <div className="d-flex flex-column">
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-5.webp"
                width={300}
                height={300}
                priority 
              />
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-3.webp"
                width={300}
                height={300}
                priority 
              />
            </div>
            <div className="d-flex flex-column">
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-7.webp"
                width={300}
                height={300}
                priority 
              />
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-8.webp"
                width={300}
                height={300}
                priority 
              />
            </div>
            <div className="d-flex flex-column">
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-9.webp"
                width={300}
                height={300}
                priority 
              />
              <Image
                className="img1 img-fluid rounded"
                src="/images/media-10.webp"
                width={300}
                height={300}
                priority 
              />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default Media;
