import React from "react";
import Head from "next/head";
function Media() {
  return (
    <div>
      <Head>
        <title>Vekser-Media Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section className="section mb-5">
        <div className="container">
          <div className="row">
            <h1 className="text-center b-5">The Vekser experience</h1>
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <div className="d-flex flex-column">
              <img
                className="img1 img-fluid rounded"
                src="./images/media-3.jpg"
              />
              <img
                className="img1 img-fluid rounded"
                src="./images/media-1.jpg"
              />
            </div>

            <div className="d-flex flex-column">
              <img
                className="img1 img-fluid rounded"
                src="./images/media-2.jpg"
              />
              <img
                className="img1 img-fluid rounded"
                src="./images/media-4.png"
              />
            </div>

            <div className="d-flex flex-column">
              <img
                className="img1 img-fluid rounded"
                src="./images/media-1.jpg"
              />
              <img
                className="img1 img-fluid rounded"
                src="./images/media-3.jpg"
              />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default Media;
