import React from "react";
import Link from "next/link";
import Head from "next/head";
import Image from 'next/image';
function Portfolio() {
  return (
    <div>
      <Head>
        <title>Vekser-Portfolio Page</title>
        <meta name="description" content="Generated by Vekser app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section className="section">
        <div className="container first-text">
          <div className="row text-center">
            <h1 className="b-5">Let's take the plunge together</h1>
          </div>
          <div className="row mt-5">
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center logodiv">
                  <Image
                    src="/images/clevertone logo black webp.webp"
                    className="img-fluid my-button"
                    alt="clevertone"
                    width={135}
                    height={150}
                    priority 
                  />
                  </div>
                  <div className="pt-4">
                  <h5 className="b-5 pt-2 hovereffect1 text-center">On-demand 24/7 AI & talented workforce to manage your day to day
</h5>
                  <p className="b-5 hovereffect text-center">
                    Coming Soon
                  </p>
                  </div>
                 
                
              </div>
            </div>
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center logodiv">
                  <Image
                    src="/images/trelegate logo webp.webp"
                    className="img-fluid my-button logo"
                    alt="trelegate"
                    width={250}
                    height={250}
                    priority 
                  />
                     </div>
                     <div className="pt-4">
                  <h5 className="b-5 hovereffect1 text-center">
                  Order wholesale products directly from verified suppliers
                  </h5>
                  <p className="b-5 hovereffect text-center">
                  Coming Soon 
                  </p>
             </div>
              </div>
            </div>
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center logodiv">
                  <Image
                    src="/images/Algorip-logo.webp"
                    className="img-fluid my-button"
                    alt="Algorip"
                    width={500}
                    height={500}
                    priority 
                  />
                      </div>
                      <div className="pt-4">
                  <h5 className="b-5 hovereffect1 text-center">
                    Software,Internet,Technology
                  </h5>
                  <p className="b-5 hovereffect text-center">
                    All-in-one platform that proactive automates and manages
                    your complete online presence.
                  </p>
                  </div>
            
              </div>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center logodiv">
                  <Image
                    src="/images/renesecent-logo.webp"
                    className="img-fluid mt-3 my-button"
                    alt="renescent"
                    width={200}
                    height={500}
                    priority 
                  />
                    </div>
                    <div className="pt-4">
                  <h5 className="b-5 hovereffect1 text-center">On Demand Logistics</h5>
                  <p className="b-5 hovereffect text-center">
                    Connecting customers with background-checked independent
                    drivers and storage providers.
                  </p>
              </div>
              </div>
            </div>
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center logodiv">
                  <Image
                    src="/images/properties-logo.webp"
                    className="img-fluid my-button"
                    alt="prroperties"
                    width={150}
                    height={100}
                    priority 
                  />
                     </div>
                     <div className="pt-4">
                  <h5 className="b-5 hovereffect1 text-center">
                    Real estate,property,rentals and management
                  </h5>
                  <p className="b-5 hovereffect text-center">
                    Best place to find ready-to-move residential and commercial
                    properties.
                  </p>
             </div>
              </div>
            </div>
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center mt-5">
                  <Image
                    src="/images/reloship-logo.webp"
                    className="img-fluid my-button"
                    alt="Reloship"
                    width={150}
                    height={150}
                    priority 
                  />
                    <div className="pt-5">
                   <h5 className="b-5 hovereffect1 text-center">
                    Global Logistics and Supply Chains
                  </h5>
                  <p className="b-5 hovereffect text-center">Founded 2007 -2010 Exit.</p>
                </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center logodiv">
                  <Image
                    src="/images/Dadadino-logo.webp"
                    className="img-fluid mt-3 my-button"
                    alt="Dandino Apparel"
                    width={200}
                    height={500}
                    priority 
                  />
                    </div>
                    <div className="pt-4">
                  <h5 className="b-5 hovereffect1 text-center"> High-end Men's and Women's Apparel</h5>
                  <p className="b-5 hovereffect text-center">
                  Founded 2001 -2006 Exit.
                  </p>
              </div>
              </div>
            </div>
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center pt-4 logodiv">
                  <Image
                    src="/images/sparoll-logo.webp"
                    className="img-fluid my-button"
                    alt="sparoll"
                    width={150}
                    height={100}
                    priority 
                  />
                     </div>
                     <div className="pt-4">
                  <h5 className="b-5 hovereffect1 text-center">
                  On-Demand Spa and Beauty
                  </h5>
                  <p className="b-5 hovereffect text-center">
                  Founded 2016 -2019 Exit.
                  </p>
             </div>
              </div>
            </div>
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center pt-4">
                  <Image
                    src="/images/takestar-logo.webp"
                    className="img-fluid my-button"
                    alt="takestar"
                    width={150}
                    height={150}
                    priority 
                  />
                    <div className="pt-5">
                   <h5 className="b-5 hovereffect1 text-center">
                   On-Demand Moving and Delivery
                  </h5>
                  <p className="b-5 hovereffect">Founded 2016 -2019 Exit.</p>
                </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-4 ">
             
            </div>
            <div className="col-md-4 ">
              <div className="card card-box p-4 divsize">
                <div className="text-center pt-4 logodiv">
                  <Image
                    src="/images/haload-logo.webp"
                    className="img-fluid my-button"
                    alt="Haload"
                    width={150}
                    height={100}
                    priority 
                  />
                     </div>
                     <div className="pt-4">
                  <h5 className="b-5 hovereffect1 text-center">
             Instant logistic quote online
                  </h5>
                  <p className="b-5 hovereffect text-center">
                  Founded 2012 -2015 Exit.
                  </p>
             </div>
              </div>
            </div>
            <div className="col-md-4 ">
             
            </div>
          </div>
    
          <div className="row mt-5 mb-5">
            <div className="text-center">
            <Link href="/media" passHref className="btn btn-primary my-button">
              View Gallery
            </Link>
            </div>
          </div>
      
          
        </div>
     

      </section>
    </div>
  );
}

export default Portfolio;
